version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_dataset_report:
    run: >
      dataset-report:v0.0.9
        --input-files output/input.feather
        --output-dir output/
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        dataset_report: output/input.html

  counts:
    run: r:latest analysis/count_tables.r
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        binary_table: output/tables/sex_ethn_binary.csv
        binary_imd_table: output/tables/sex_ethn_binary_imd.csv
        binary_5_table: output/tables/sex_ethn_5.csv
        binary_16_table: output/tables/sex_ethn_16.csv